apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: test
  namespace: ""
endpoint: ""
token: ""
export:
  power:
    type: jumpstarter_driver_power.driver.MockPower
  storage:
    type: jumpstarter_driver_opendal.driver.MockStorageMux
  serial:
    type: jumpstarter_driver_pyserial.driver.PySerial
    config:
      url: "loop://"
